/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2024-09-10 00:04:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/pagina/menu.jsp", Long.valueOf(1725915690000L));
    _jspx_dependants.put("/pagina/footer.jsp", Long.valueOf(1725838172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Info4Cloud</title>\r\n");
      out.write("<!-- Incluindo o CSS do Bootstrap 4 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<!-- JavaScript do Bootstrap 4 -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<link href=\"CSS/estilo.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	$(document)\r\n");
      out.write("			.ready(\r\n");
      out.write("					function() {\r\n");
      out.write("						// Chama a função carregarClassificacoes ao carregar a página\r\n");
      out.write("						carregarClassificacoes();\r\n");
      out.write("\r\n");
      out.write("						// Função de busca na tabela\r\n");
      out.write("						$('#inputBusca')\r\n");
      out.write("								.on(\r\n");
      out.write("										'keyup',\r\n");
      out.write("										function() {\r\n");
      out.write("											var valorBusca = $(this).val()\r\n");
      out.write("													.toLowerCase();\r\n");
      out.write("											$('#tabelaClassificacoes tbody tr')\r\n");
      out.write("													.filter(\r\n");
      out.write("															function() {\r\n");
      out.write("																$(this)\r\n");
      out.write("																		.toggle(\r\n");
      out.write("																				$(\r\n");
      out.write("																						this)\r\n");
      out.write("																						.text()\r\n");
      out.write("																						.toLowerCase()\r\n");
      out.write("																						.indexOf(\r\n");
      out.write("																								valorBusca) > -1);\r\n");
      out.write("															});\r\n");
      out.write("										});\r\n");
      out.write("					});\r\n");
      out.write("\r\n");
      out.write("	// Função para carregar classificações\r\n");
      out.write("	function carregarClassificacoes() {\r\n");
      out.write("		$\r\n");
      out.write("				.ajax({\r\n");
      out.write("					url : '/agro/ClassificacaoServlet', // Verifique se a URL está correta\r\n");
      out.write("					method : 'GET',\r\n");
      out.write("					timeout : 2000,\r\n");
      out.write("					dataType : 'json',\r\n");
      out.write("					success : function(data) {\r\n");
      out.write("						if (data.length === 0) {\r\n");
      out.write("							alert('Não há dados disponíveis.'); // Alerta de erro\r\n");
      out.write("							$('#tabelaClassificacoes').hide(); // Esconde a tabela\r\n");
      out.write("							$('#divBusca').hide(); // Esconde a div do campo de busca\r\n");
      out.write("							$('#btnCadastro').removeClass('mt-3').addClass(\r\n");
      out.write("									'mt-4'); // Ajusta margem do botão\r\n");
      out.write("						} else {\r\n");
      out.write("							$('#tabelaClassificacoes tbody').empty(); // Limpa a tabela\r\n");
      out.write("							$('#tabelaClassificacoes').show(); // Mostra a tabela\r\n");
      out.write("							$('#divBusca').show(); // Mostra a div do campo de busca\r\n");
      out.write("							$('#btnCadastro').removeClass('mt-4').addClass(\r\n");
      out.write("									'mt-3'); // Ajusta margem do botão\r\n");
      out.write("							// Itera sobre os dados recebidos e cria as linhas da tabela\r\n");
      out.write("							$\r\n");
      out.write("									.each(\r\n");
      out.write("											data,\r\n");
      out.write("											function(index, classificacao) {\r\n");
      out.write("												var linha = '<tr>'\r\n");
      out.write("														+ '<td>'\r\n");
      out.write("														+ classificacao.idclassificacao\r\n");
      out.write("														+ '</td>'\r\n");
      out.write("														+ '<td>'\r\n");
      out.write("														+ classificacao.classificacao\r\n");
      out.write("														+ '</td>'\r\n");
      out.write("														+ '<td>'\r\n");
      out.write("														+ '<button class=\"btn btn-sm btn-warning btn-responsivo\" onclick=\"abrirModalAtualizacao('\r\n");
      out.write("														+ classificacao.idclassificacao\r\n");
      out.write("														+ ', \\''\r\n");
      out.write("														+ classificacao.classificacao\r\n");
      out.write("														+ '\\')\"><i class=\"fas fa-sync\"></i><span class=\"texto-botao\">Atualizar</span></button> '\r\n");
      out.write("														+ '<button class=\"btn btn-sm btn-danger btn-responsivo\" onclick=\"abrirModalExclusao('\r\n");
      out.write("														+ classificacao.idclassificacao\r\n");
      out.write("														+ ', \\''\r\n");
      out.write("														+ classificacao.classificacao\r\n");
      out.write("														+ '\\')\"><i class=\"fas fa-trash-alt\"></i><span class=\"texto-botao\">Excluir</span></button>'\r\n");
      out.write("														+ '</td>' + '</tr>';\r\n");
      out.write("												$('#tabelaClassificacoes tbody')\r\n");
      out.write("														.append(linha);\r\n");
      out.write("											});\r\n");
      out.write("						}\r\n");
      out.write("					},\r\n");
      out.write("					error : function(xhr, status, error) {\r\n");
      out.write("						// Log detalhado do erro para depuração\r\n");
      out.write("						console.error('Erro ao carregar classificações:',\r\n");
      out.write("								status, error);\r\n");
      out.write("						console\r\n");
      out.write("								.error('Detalhes da resposta:',\r\n");
      out.write("										xhr.responseText);\r\n");
      out.write("						alert('Erro ao carregar classificações.');\r\n");
      out.write("						$('#tabelaClassificacoes').hide(); // Esconde a tabela em caso de erro\r\n");
      out.write("						$('#divBusca').hide(); // Esconde a div do campo de busca\r\n");
      out.write("						$('#btnCadastro').removeClass('mt-3').addClass('mt-4'); // Ajusta margem do botão\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// Função para abrir o modal de atualização e preencher o formulário com os dados atuais\r\n");
      out.write("	function abrirModalAtualizacao(id, classificacao) {\r\n");
      out.write("		$('#atualizacaoId').val(id);\r\n");
      out.write("		$('#atualizacaoClassificacao').val(classificacao);\r\n");
      out.write("		$('#modalAtualizacao').modal('show');\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// Função para abrir o modal de confirmação de exclusão\r\n");
      out.write("	function abrirModalExclusao(id, classificacao) {\r\n");
      out.write("		$('#exclusaoId').val(id);\r\n");
      out.write("		$('#exclusaoClassificacao').val(classificacao);\r\n");
      out.write("		$('#modalExclusao').modal('show');\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// Função para salvar a nova classificação\r\n");
      out.write("	function salvarClassificacao() {\r\n");
      out.write("		var classificacao = $('#classificacao').val();\r\n");
      out.write("\r\n");
      out.write("		if (classificacao.trim() === '') {\r\n");
      out.write("			alert('Por favor, preencha a classificação.');\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// Envia os dados da nova classificação para o servidor\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : '/agro/ClassificacaoServlet',\r\n");
      out.write("			method : 'POST',\r\n");
      out.write("			data : {\r\n");
      out.write("				classificacao : classificacao\r\n");
      out.write("			},\r\n");
      out.write("			success : function(response) {\r\n");
      out.write("				alert(response.message)\r\n");
      out.write("				$('#modalCadastro').modal('hide');\r\n");
      out.write("				classificacao = $('#classificacao').val(\"\")// Fecha o modal após salvar\r\n");
      out.write("				carregarClassificacoes(); // Recarrega as classificações para atualizar a tabela\r\n");
      out.write("			},\r\n");
      out.write("			error : function(xhr) {\r\n");
      out.write("				alert('Erro ao cadastrar classificação: '\r\n");
      out.write("						+ xhr.responseJSON.error);\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function atualizarClassificacao() {\r\n");
      out.write("		var id = $('#atualizacaoId').val();\r\n");
      out.write("		var classificacao = $('#atualizacaoClassificacao').val();\r\n");
      out.write("		var acao = $('#acao').val();\r\n");
      out.write("\r\n");
      out.write("		if (classificacao.trim() === '') {\r\n");
      out.write("			alert('Por favor, preencha a classificação.');\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		// Log para verificar os dados que estão sendo enviados\r\n");
      out.write("		console.log('Enviando dados:', {\r\n");
      out.write("			id : id,\r\n");
      out.write("			classificacao : classificacao\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		// Envia os dados atualizados para o servidor usando PUT\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : '/agro/ClassificacaoServlet',\r\n");
      out.write("			method : 'POST',\r\n");
      out.write("\r\n");
      out.write("			data : {\r\n");
      out.write("				id : id,\r\n");
      out.write("				classificacao : classificacao,\r\n");
      out.write("			},\r\n");
      out.write("			success : function(response) {\r\n");
      out.write("				alert(response.message);\r\n");
      out.write("				console.log(response);\r\n");
      out.write("				$('#modalAtualizacao').modal('hide'); // Fecha o modal após atualizar\r\n");
      out.write("				carregarClassificacoes(); // Recarrega as classificações para atualizar a tabela\r\n");
      out.write("			},\r\n");
      out.write("			error : function(xhr) {\r\n");
      out.write("\r\n");
      out.write("				alert('Erro ao atualizar classificação: '\r\n");
      out.write("						+ (xhr.responseJSON ? xhr.responseJSON.error\r\n");
      out.write("								: 'Erro desconhecido'));\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	// Função para excluir a classificação\r\n");
      out.write("	function excluirClassificacao() {\r\n");
      out.write("		var id = $('#exclusaoId').val();\r\n");
      out.write("		var acao = \"Delete\";\r\n");
      out.write("		console.log(acao);\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url : '/agro/ClassificacaoServlet',\r\n");
      out.write("			method : 'POST',\r\n");
      out.write("			data : {\r\n");
      out.write("				id : id,\r\n");
      out.write("				acao : acao,\r\n");
      out.write("			},\r\n");
      out.write("			success : function(response) {\r\n");
      out.write("				alert(response.message);\r\n");
      out.write("				$('#modalExclusao').modal('hide'); // Feche o modal após excluir\r\n");
      out.write("				carregarClassificacoes(); // Recarrega as classificações para atualizar a tabela\r\n");
      out.write("			},\r\n");
      out.write("			error : function(xhr) {\r\n");
      out.write("				console.error('Erro ao Excluir:', xhr.responseText);\r\n");
      out.write("				alert('Erro ao Excluir: '\r\n");
      out.write("						+ (xhr.responseJSON ? xhr.responseJSON.error\r\n");
      out.write("								: 'Erro desconhecido'));\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-success\">\r\n");
      out.write("	<a class=\"navbar-brand\" href=\"#\">Info4Cloud</a>\r\n");
      out.write("	<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("		data-target=\"#navbarNav\" aria-controls=\"navbarNav\"\r\n");
      out.write("		aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("		<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("	</button>\r\n");
      out.write("	<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("		<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link active\" href=\"#\">Classificações</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Relatórios</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li class=\"nav-item dropdown\"><a\r\n");
      out.write("				class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("				role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("				aria-expanded=\"false\">Configuração</a>\r\n");
      out.write("				<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("					<a class=\"dropdown-item\" href=\"http://localhost:8080/agro/Admin/classificacao.jsp\">Classificação</a> <a class=\"dropdown-item\"\r\n");
      out.write("						href=\"#\">Outra ação</a>\r\n");
      out.write("					<div class=\"dropdown-divider\"></div>\r\n");
      out.write("					<a class=\"dropdown-item\" href=\"#\">Algo mais aqui</a>\r\n");
      out.write("				</div></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Perfil</a></li>\r\n");
      out.write("			<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Sair</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("	<div class=\"container-fluid content mt-2\">\r\n");
      out.write("		<h2\r\n");
      out.write("			class=\"mb-2 text-white border bg-success p-2 rounded shadow-custom\">Classificações</h2>\r\n");
      out.write("		<!-- Div para o campo de busca -->\r\n");
      out.write("		<div id=\"divBusca\" class=\"mb-3 bg-success p-2 rounded shadow-custom\"\r\n");
      out.write("			style=\"display: none;\">\r\n");
      out.write("			<h6 class=\"mb-1 text-white\">Buscar</h6>\r\n");
      out.write("			<input id=\"inputBusca\" type=\"text\" class=\"form-control\"\r\n");
      out.write("				placeholder=\"Buscar classificação...\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"table-responsive  rounded shadow-custom\">\r\n");
      out.write("			<table id=\"tabelaClassificacoes\"\r\n");
      out.write("				class=\"table table-bordered table-striped\" style=\"display: none;\">\r\n");
      out.write("				<thead class=\"thead-green\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>ID Classificação</th>\r\n");
      out.write("						<th>Classificação</th>\r\n");
      out.write("						<th>Ações</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<!-- Dados serão inseridos dinamicamente aqui -->\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Botão para abrir o modal de cadastro -->\r\n");
      out.write("		<button id=\"btnCadastro\" type=\"button\" class=\"btn btn-primary mt-4\"\r\n");
      out.write("			data-toggle=\"modal\" data-target=\"#modalCadastro\">\r\n");
      out.write("			<i class=\"fas fa-plus\"></i> <span class=\"texto-botao\">Classificação</span>\r\n");
      out.write("		</button>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal de Cadastro de Classificação -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"modal fade\" id=\"modalCadastro\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("		aria-labelledby=\"modalCadastroLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"modalCadastroLabel\">Cadastrar\r\n");
      out.write("						Classificação</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<form id=\"formCadastro\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"classificacao\">Classificação</label> <input\r\n");
      out.write("								type=\"text\" class=\"form-control\" id=\"classificacao\"\r\n");
      out.write("								name=\"classificacao\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Cancelar</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("						onclick=\"salvarClassificacao()\">Salvar</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal de Atualização de Classificação -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"modalAtualizacao\" tabindex=\"-1\"\r\n");
      out.write("		role=\"dialog\" aria-labelledby=\"modalAtualizacaoLabel\"\r\n");
      out.write("		aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"modalAtualizacaoLabel\">Atualizar\r\n");
      out.write("						Classificação</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<form id=\"formAtualizacao\">\r\n");
      out.write("						<input type=\"hidden\" id=\"atualizacaoId\" name=\"atualizacaoId\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label for=\"atualizacaoClassificacao\">Classificação</label> <input\r\n");
      out.write("								type=\"text\" class=\"form-control\" id=\"atualizacaoClassificacao\"\r\n");
      out.write("								name=\"atualizacaoClassificacao\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("						onclick=\"atualizarClassificacao()\">Atualizar</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Cancelar</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Modal de Confirmação de Exclusão -->\r\n");
      out.write("	<div class=\"modal fade\" id=\"modalExclusao\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("		aria-labelledby=\"modalExclusaoLabel\" aria-hidden=\"true\">\r\n");
      out.write("		<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h5 class=\"modal-title\" id=\"modalExclusaoLabel\">Confirmar\r\n");
      out.write("						Exclusão</h5>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("						aria-label=\"Close\">\r\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("					<p></p>\r\n");
      out.write("					<form id=\"Excluir\">\r\n");
      out.write("						<input type=\"text\" id=\"exclusaoId\" name=\"exclusaoId\"> <input\r\n");
      out.write("							type=\"hidden\" id=\"deletar\" value=\"Delete\"> <input\r\n");
      out.write("							type=\"text\" id=\"exclusaoClassificacao\">\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-danger\"\r\n");
      out.write("						onclick=\"excluirClassificacao()\">Excluir</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("						data-dismiss=\"modal\">Cancelar</button>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<footer>\r\n");
      out.write("		");
      out.write("<footer class=\"bg-success text-white text-center p-3\">\r\n");
      out.write("    <p class=\"mb-0\">Info4cloud</p>\r\n");
      out.write(" \r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
